# name: stats2
# channels:
#   - javascript
# dependencies:
#   - python=3.9
#   - bokeh=2.4.2
#   - conda-forge::numpy=1.21.*
#   - nodejs=16.13.*
#   - matplotlib
#   - pandas
#   - scikit-learn
#   - pip
#   - pip:
#     - web_anno_tsv

name: master_thesis_2023
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl
  - pandas
  - mlflow
  - scikit-learn
  - pytorch-lightning
  - pip:
    - torchviz
    # - web_anno_tsv